language: node_js
node_js:
  - 5
  - 6
  - 7

cache:
  directories:
    - node_modules
    - typings

before_install:
  - npm i yarn typings nyc -g

install:
  - yarn --pure-lockfile
  - typings i

before_script:
  - yarn compile

script:
  - yarn lint
  - yarn test
  - nyc report -r=text-lcov | ./node_modules/.bin/codecov

branches:
  only:
    - master
