language: node_js
node_js:
  - '4'
  - '5'
  - '6'

cache:
  directories:
    - node_modules
    - typings

before_install:
  - npm i yarn typings -g

install:
  - yarn
  - typings i

before_script:
  - yarn compile

script:
  - yarn lint
  - yarn test
  - cat ./coverage/lcov.info | ./node_modules/.bin/codecov

branches:
  only:
    - master
