language: node_js
node_js:
  - 6      
  - 8
  - 9

cache:
  directories:
    - node_modules

before_install:
  - npm i yarn nyc -g

install:
  - yarn --pure-lockfile

before_script:
  - yarn build

script:
  - yarn lint
  - yarn test
  - nyc report -r=text-lcov | ./node_modules/.bin/codecov
