language: node_js
node_js:
  - '4'
  - '5'
  - '6'

cache:
  directories:
    - node_modules
    - typings

install:
  - npm i typings rimraf
  - npm i
  - typings i

before_script:
  - npm prune
  - npm run compile

script:
  - npm run lint
  - npm test
  - cat ./coverage/lcov.info | ./node_modules/.bin/codecov

branches:
  only:
    - master

